language: node_js
node_js:  
  - "node"

services:
  - mysql

env: TEST_MYSQL_USERNAME=root TEST_MYSQL_PASSWORD="" DATABASE="testAsssignment"

stages:
  - build

jobs:
  include: 
      stage: build
      env: TEST_MYSQL_USERNAME=root TEST_MYSQL_PASSWORD="" DATABASE="testAsssignment" 
      script: 
        - cd assignments/Assignment4
        - npm i;
        - mysql -u root < ./sql.sql
        - npm run test 